modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="smooth_time"
version="${version}"
displayName="Smooth Time"
description='''Smooths the client-side sky time at the render frame rate.'''
logoFile="assets/smooth_time/icon.png"
logoBlur=false
authors="skuto"

[[mixins]]
config="smooth_time.mixins.json"

[[dependencies.smooth_time]]
modId="neoforge"
type="required"
versionRange="[21.1.213,)"
ordering="NONE"
side="CLIENT"

[[dependencies.smooth_time]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="CLIENT"
